/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.docgia_Dao;
import DAO.phieumuon_Dao;
import DAO.sach_Dao;
import Model.docgia;
import Model.phieumuon;
import Model.sach;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TechCare
 */
public class AdminQuanLySach extends javax.swing.JFrame {
        DefaultTableModel tableModelPM;
        DefaultTableModel tableModelDG;
        DefaultTableModel tableModelS;
    List<sach> sachList = new ArrayList<>();
    List<docgia> docgiaList = new ArrayList<>();
    List<phieumuon> phieumuonList = new ArrayList<>();
        
    /**
     * Creates new form AdminQuanLySach
     */
    public AdminQuanLySach() {
                initComponents();

        
        tableModelPM = (DefaultTableModel) tblPhieumuon.getModel();
        showPhieumuon();
        
      tableModelDG = (DefaultTableModel) tblDocgia.getModel();
        showDocgia();
        
        tableModelS = (DefaultTableModel) tblSach.getModel();
        showSach();
    }
    private void showSach() {
       sachList = sach_Dao.findAll();
        
        tableModelS.setRowCount(0);
        
        sachList.forEach((sach) -> {
            tableModelS.addRow(new Object[] {tableModelS.getRowCount() + 1, sach.getTensach_53(), 
                sach.getTentheloai_53(), sach.getTendanhmuc_53(),sach.getTacgia_53(),sach.getNhaxuatban_53(),
            sach.getNgayxuatban_53(),sach.getTomtat_53()});
        });
    }
        private void showDocgia() {
       docgiaList = docgia_Dao.findAll();
        
        tableModelDG.setRowCount(0);
        
        docgiaList.forEach((docgia) -> {
            tableModelDG.addRow(new Object[] {tableModelDG.getRowCount() + 1, docgia.getTendocgia(), 
                docgia.getSdt(), docgia.getEmail(),docgia.getDiachi()});
        });
    }
           private void showPhieumuon() {
       phieumuonList = phieumuon_Dao.findAll();
        
        tableModelPM.setRowCount(0);
        
        phieumuonList.forEach((phieumuon) -> {
            tableModelPM.addRow(new Object[] {tableModelPM.getRowCount() + 1, phieumuon.getMadocgiamuon_15(), 
              phieumuon.getMasachmuon_15(), phieumuon.getNgaymuon_15()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtMasach = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtTensach = new javax.swing.JTextField();
        txtTentheloai = new javax.swing.JTextField();
        txtTendanhmuc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtTentacgia = new javax.swing.JTextField();
        txtNhaxuatban = new javax.swing.JTextField();
        txtNgayxuatban = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTomtat = new javax.swing.JTextArea();
        butThem = new javax.swing.JButton();
        butResetS = new javax.swing.JButton();
        butXoa = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        butTimkiem = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtMaphieumuon = new javax.swing.JTextField();
        txtMadocgiamuon = new javax.swing.JTextField();
        butThemPM = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhieumuon = new javax.swing.JTable();
        txtMasachmuon = new javax.swing.JTextField();
        txtNgaymuon = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        butXoaPM = new javax.swing.JButton();
        butTimkiemPM = new javax.swing.JButton();
        butResetPM = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtSoluongSach = new javax.swing.JTextField();
        txtSoluongKhachmuon = new javax.swing.JTextField();
        txtSoluongDG = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMadocgia = new javax.swing.JTextField();
        txtTendocgia = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        butThemDG = new javax.swing.JButton();
        butXoaDG = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDocgia = new javax.swing.JTable();
        butTimkiemDG = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ SÁCH");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Trường Đại Học Sư Phạm Kỹ Thuật Đà Nẵng");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageTrangChuChinh/logo-truong-250.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(213, 213, 213))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(153, 255, 153));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jPanel12.setBackground(new java.awt.Color(255, 204, 204));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Mã sách:");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Tên sách :");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Tên thể loại");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("Tên danh mục : ");

        txtTendanhmuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTendanhmucActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Tác giả :");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setText("Nhà xuất bản");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setText("Ngày xuất bản :");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setText("Tóm tắt nội dung :");

        txtTomtat.setColumns(20);
        txtTomtat.setRows(5);
        jScrollPane3.setViewportView(txtTomtat);

        butThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageQuanly/plus.png"))); // NOI18N
        butThem.setText("Thêm");
        butThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butThemActionPerformed(evt);
            }
        });

        butResetS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageQuanly/reset.png"))); // NOI18N
        butResetS.setText("Reset");
        butResetS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butResetSActionPerformed(evt);
            }
        });

        butXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageQuanly/delete.png"))); // NOI18N
        butXoa.setText("Xóa");
        butXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butXoaActionPerformed(evt);
            }
        });

        tblSach.setBackground(new java.awt.Color(255, 255, 204));
        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Tên thể loại", "Tên danh mục", "Tác giả", "Nhà xuất bản", "Ngày xuất bản", "Tóm tắt"
            }
        ));
        jScrollPane4.setViewportView(tblSach);

        butTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageQuanly/search.png"))); // NOI18N
        butTimkiem.setText("Tim kiem");
        butTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMasach, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                .addComponent(txtTensach)
                                .addComponent(txtTentheloai)
                                .addComponent(txtTendanhmuc)
                                .addComponent(txtTentacgia))
                            .addGap(52, 52, 52)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel23)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(30, 30, 30)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNgayxuatban, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNhaxuatban, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3)))
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addGap(170, 170, 170)
                            .addComponent(butTimkiem)
                            .addGap(18, 18, 18)
                            .addComponent(butThem)
                            .addGap(18, 18, 18)
                            .addComponent(butResetS)
                            .addGap(18, 18, 18)
                            .addComponent(butXoa))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtMasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtNhaxuatban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTensach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txtNgayxuatban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtTentheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtTendanhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTentacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butThem)
                    .addComponent(butResetS)
                    .addComponent(butXoa)
                    .addComponent(butTimkiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("  QUẢN LÝ SÁCH", new javax.swing.ImageIcon(getClass().getResource("/imageQuanly/book (1).png")), jPanel5); // NOI18N

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Mã phiếu mượn: ");

        butThemPM.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        butThemPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageQuanly/plus.png"))); // NOI18N
        butThemPM.setText("Thêm");
        butThemPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butThemPMActionPerformed(evt);
            }
        });

        tblPhieumuon.setBackground(new java.awt.Color(255, 204, 204));
        tblPhieumuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã phiếu mượn", "Mã đọc giả mượn", "Mã sách mượn", "Ngày mượn"
            }
        ));
        jScrollPane2.setViewportView(tblPhieumuon);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Ngày mượn : ");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Mã sách: ");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Mã đọc giả mượn: ");

        butXoaPM.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        butXoaPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageQuanly/delete.png"))); // NOI18N
        butXoaPM.setText("Xóa");
        butXoaPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butXoaPMActionPerformed(evt);
            }
        });

        butTimkiemPM.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        butTimkiemPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageQuanly/search.png"))); // NOI18N
        butTimkiemPM.setText("Tìm kiếm");
        butTimkiemPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTimkiemPMActionPerformed(evt);
            }
        });

        butResetPM.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        butResetPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageQuanly/reset.png"))); // NOI18N
        butResetPM.setText("Reset");
        butResetPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butResetPMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(41, 41, 41))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(txtNgaymuon, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                .addGap(63, 63, 63)
                                .addComponent(butTimkiemPM))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtMasachmuon)
                                    .addComponent(txtMaphieumuon, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(txtMadocgiamuon, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(butThemPM, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(butXoaPM, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(butResetPM, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaphieumuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butThemPM))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMadocgiamuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(butXoaPM))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMasachmuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(butResetPM))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(butTimkiemPM))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("QUẢN LÝ MƯỢN SÁCH", new javax.swing.ImageIcon(getClass().getResource("/imageQuanly/menu.png")), jPanel4); // NOI18N

        jPanel6.setBackground(new java.awt.Color(153, 255, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("SỐ LIỆU THỐNG KÊ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Số lượng sách còn trong kho :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Số lượng đọc giả đã đăng ký :");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("Số lượng sách đã mượn         :");

        jButton1.setText("Làm mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoluongDG, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoluongKhachmuon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoluongSach, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(488, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSoluongSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSoluongDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoluongKhachmuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("THỐNG KÊ", new javax.swing.ImageIcon(getClass().getResource("/imageQuanly/analysis.png")), jPanel6); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Mã đọc giả:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Tên đọc giả:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("SĐT :");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Địa chỉ:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Email :");

        butThemDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageQuanly/plus.png"))); // NOI18N
        butThemDG.setText("Thêm ");
        butThemDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butThemDGActionPerformed(evt);
            }
        });

        butXoaDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageQuanly/delete.png"))); // NOI18N
        butXoaDG.setText("Xóa");
        butXoaDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butXoaDGActionPerformed(evt);
            }
        });

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageQuanly/reset.png"))); // NOI18N
        jButton14.setText("Reset");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        tblDocgia.setBackground(new java.awt.Color(102, 255, 204));
        tblDocgia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã đọc giả", "Tên đọc giả", "SĐT", "Email", "Địa chỉ"
            }
        ));
        jScrollPane6.setViewportView(tblDocgia);

        butTimkiemDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageQuanly/search.png"))); // NOI18N
        butTimkiemDG.setText("Tìm kiếm");
        butTimkiemDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTimkiemDGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtMadocgia, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTendocgia, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(butTimkiemDG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(butXoaDG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(butThemDG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMadocgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butThemDG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTendocgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butXoaDG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butTimkiemDG))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("QUẢN LÝ ĐỌC GIẢ", new javax.swing.ImageIcon(getClass().getResource("/imageQuanly/people (1).png")), jPanel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTendanhmucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTendanhmucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTendanhmucActionPerformed

    private void butThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butThemActionPerformed
        String tensach = txtTensach.getText();
        String tentheloai = txtTentheloai.getText();
        String tendanhmuc = txtTendanhmuc.getText();
        String tacgia = txtTentacgia.getText();
        String nhaxuatban = txtNhaxuatban.getText();
        String ngayxuatban = txtNgayxuatban.getText();
        String tomtat = txtTomtat.getText();
        
        sach s = new sach(tensach, tentheloai,tendanhmuc,tacgia,nhaxuatban,ngayxuatban,tomtat);
        
        sach_Dao.insert(s);
     showSach();
    }//GEN-LAST:event_butThemActionPerformed

    private void butXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butXoaActionPerformed
       int selectedIndex = tblSach.getSelectedRow();
        if(selectedIndex >= 0) {
            sach s = sachList.get(selectedIndex);
            
            int option = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa sách này ?");
            System.out.println("option : " + option);
            
            if(option == 0) {
                sach_Dao.delete(s.getMasach_53());
                
                showSach();
            }
        }      
    }//GEN-LAST:event_butXoaActionPerformed

    private void butThemDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butThemDGActionPerformed
        String tendocgia = txtTendocgia.getText();
        String sdt = txtSdt.getText();
        String email = txtEmail.getText();
        String diachi = txtDiachi.getText();

        
        docgia dg = new docgia(tendocgia, sdt,email,diachi);
        
        docgia_Dao.insert(dg);
     showDocgia();
    }//GEN-LAST:event_butThemDGActionPerformed

    private void butXoaDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butXoaDGActionPerformed
          int selectedIndex = tblDocgia.getSelectedRow();
        if(selectedIndex >= 0) {
            docgia dg = docgiaList.get(selectedIndex);
            
            int option = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa người dùng này ?");
            System.out.println("option : " + option);
            
            if(option == 0) {
                docgia_Dao.delete(dg.getMadocgia());
                
                showDocgia();
            }
        }      
    }//GEN-LAST:event_butXoaDGActionPerformed

    private void butTimkiemDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTimkiemDGActionPerformed
        String input = JOptionPane.showInputDialog(this, "Nhập tên đọc giả cần tìm kiếm !!!!");
        if(input != null && input.length() > 0) {
            docgiaList = docgia_Dao.findByFullname(input);
            
            tableModelDG.setRowCount(0);
        
       docgiaList.forEach((docgia) -> {
            tableModelDG.addRow(new Object[] {tableModelDG.getRowCount() + 1, docgia.getTendocgia(), 
                docgia.getSdt(), docgia.getEmail(),docgia.getDiachi()});
        });
        }else {
            showDocgia();
            
        }
        
    }//GEN-LAST:event_butTimkiemDGActionPerformed

    private void butTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTimkiemActionPerformed
        String input = JOptionPane.showInputDialog(this, "Nhập tên sách cần tìm kiếm !!!!");
        if(input != null && input.length() > 0) {
            sachList = sach_Dao.findByFullname(input);
            
            tableModelS.setRowCount(0);
        
       sachList.forEach((sach) -> {
            tableModelS.addRow(new Object[] {tableModelS.getRowCount() + 1, sach.getTensach_53(), 
                sach.getTentheloai_53(), sach.getTendanhmuc_53(),sach.getTacgia_53(),sach.getNhaxuatban_53(),
            sach.getNgayxuatban_53(),sach.getTomtat_53()});
        });
        } else {
            showSach();
        }
    }//GEN-LAST:event_butTimkiemActionPerformed

    private void butThemPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butThemPMActionPerformed
       String madocgiamuon = txtMadocgiamuon.getText();
        String masachmuon = txtMasachmuon.getText();
        String ngaymuon = txtNgaymuon.getText();

        phieumuon pm = new phieumuon(madocgiamuon, masachmuon,ngaymuon);
        
        phieumuon_Dao.insert(pm);
     showPhieumuon();
    }//GEN-LAST:event_butThemPMActionPerformed

    private void butXoaPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butXoaPMActionPerformed
          int selectedIndex = tblPhieumuon.getSelectedRow();
        if(selectedIndex >= 0) {
            phieumuon pm = phieumuonList.get(selectedIndex);
            
            int option = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa phiếu mượn này ?");
            System.out.println("option : " + option);
            
            if(option == 0) {
                phieumuon_Dao.delete(pm.getMaphieumuon_15());
                
                showPhieumuon();
            }
        }  
    }//GEN-LAST:event_butXoaPMActionPerformed

    private void butTimkiemPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTimkiemPMActionPerformed
        String input = JOptionPane.showInputDialog(this, "Nhập mã đọc giả cần tìm kiếm !!!!");
        if(input != null && input.length() > 0) {
            phieumuonList = phieumuon_Dao.findByFullname(input);
            
            tableModelPM.setRowCount(0);
        
       phieumuonList.forEach((phieumuon) -> {
            tableModelPM.addRow(new Object[] {tableModelPM.getRowCount() + 1, phieumuon.getMadocgiamuon_15(), 
                phieumuon.getMasachmuon_15(), phieumuon.getNgaymuon_15()});
        });
        }else {
            showPhieumuon();
        }
        
    }//GEN-LAST:event_butTimkiemPMActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int sosach = tblSach.getRowCount();
        int sodocgia = tblDocgia.getRowCount();
        int sopm = tblPhieumuon.getRowCount();
        txtSoluongSach.setText  (""+sosach);
        txtSoluongDG.setText  (""+sodocgia);
        txtSoluongKhachmuon.setText  (""+sopm);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void butResetSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butResetSActionPerformed
        txtTensach.getText();
        txtTentheloai.setText("");
        txtTendanhmuc.setText("");
        txtTentacgia.setText("");
        txtNhaxuatban.setText("");
        txtNgayxuatban.setText("");
        txtTomtat.setText("");
    }//GEN-LAST:event_butResetSActionPerformed

    private void butResetPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butResetPMActionPerformed
        txtMadocgiamuon.setText("");
        txtMasachmuon.setText("");
        txtNgaymuon.setText("");
    }//GEN-LAST:event_butResetPMActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        txtTendocgia.setText("");
        txtSdt.setText("");
        txtEmail.setText("");
        txtDiachi.setText("");
    }//GEN-LAST:event_jButton14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminQuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminQuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminQuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminQuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminQuanLySach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butResetPM;
    private javax.swing.JButton butResetS;
    private javax.swing.JButton butThem;
    private javax.swing.JButton butThemDG;
    private javax.swing.JButton butThemPM;
    private javax.swing.JButton butTimkiem;
    private javax.swing.JButton butTimkiemDG;
    private javax.swing.JButton butTimkiemPM;
    private javax.swing.JButton butXoa;
    private javax.swing.JButton butXoaDG;
    private javax.swing.JButton butXoaPM;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblDocgia;
    private javax.swing.JTable tblPhieumuon;
    private javax.swing.JTable tblSach;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMadocgia;
    private javax.swing.JTextField txtMadocgiamuon;
    private javax.swing.JTextField txtMaphieumuon;
    private javax.swing.JTextField txtMasach;
    private javax.swing.JTextField txtMasachmuon;
    private javax.swing.JTextField txtNgaymuon;
    private javax.swing.JTextField txtNgayxuatban;
    private javax.swing.JTextField txtNhaxuatban;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtSoluongDG;
    private javax.swing.JTextField txtSoluongKhachmuon;
    private javax.swing.JTextField txtSoluongSach;
    private javax.swing.JTextField txtTendanhmuc;
    private javax.swing.JTextField txtTendocgia;
    private javax.swing.JTextField txtTensach;
    private javax.swing.JTextField txtTentacgia;
    private javax.swing.JTextField txtTentheloai;
    private javax.swing.JTextArea txtTomtat;
    // End of variables declaration//GEN-END:variables
}
